SubInvestorSetup/Models/ReportingInvestorLink.cs
namespace SubInvestorSetup.Models
{
    public class ReportingInvestorLink
    {
        public int RI_Code { get; set; }
        public string INVESTOR_NBR { get; set; }
        public string INVESTOR_SUB { get; set; }

    }
}

SubInvestorSetup/Controllers/InvestorLinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SubInvestorSetup.Models;
using Microsoft.AspNetCore.Identity;
using SubInvestorSetup.Interface;
using Microsoft.AspNetCore.Authorization;

namespace SubInvestorSetup.Controllers
{

 
    public class InvestorLinkController : Controller
    {
        private readonly InvestorContext _context;
        private readonly IInvestorLink _investorLink;

        public InvestorLinkController(InvestorContext context, IInvestorLink investorLinkInject)
        {
            _context = context;
            _investorLink = investorLinkInject;
        }

        // GET: InvestorLink
        public async Task<IActionResult> Index()
        {
            var investorLink = await _context.InvestorLinks.ToListAsync();            

            return View(investorLink.OrderByDescending(i => i.InvestorSetupId));
            //return View(await _context.InvestorLinks.ToListAsync());
        }

        // GET: InvestorLink/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var investorLink = await _context.InvestorLinks
            //    .FirstOrDefaultAsync(m => m.InvestorSetupId == id);


            //Interface for Dependancy Injection

            //var investorLink = _investorLinkRepo.GetInvestorLink(id);
            var investorLink = _investorLink.GetInvestorLinkSubInvestors(id);


            if (investorLink == null)
            {
                return NotFound();
            }

            return View(investorLink);
        }

        // GET: InvestorLink/Create
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: InvestorLink/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create([Bind("InvestorSetupId,Description,InvestorNo,InvestorSubFrom,InvestorSubTo,ModelAfterInvestorNo,ModelAfterInvestorSub,CreatedDate,CreatedBy,ApprovedDate,ApprovedBy,DeployedDate,DeployedBy,DeletedDate,DeletedBy,DeletedReason,Status = 1")] InvestorLink investorLink)
        {


            if (ModelState.IsValid)
                try
                {

                    investorLink.Status = EnumStatus.New;
                    investorLink.CreatedDate = DateTime.Now;
                    investorLink.CreatedBy = User.Identity.Name;
                    _context.Add(investorLink);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }


            return View(investorLink);
        }

        // GET: InvestorLink/Delete/5
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {

            //if (id == null)
            //{
            //    return NotFound();
            //}

            //var model = new ReportingInvestorViewModel();

            //var investorLink = await _context.InvestorLinks
            //    .FirstOrDefaultAsync(m => m.InvestorSetupId == id);

            //if (investorLink == null)
            //{
            //    return NotFound();
            //}

            //model.InvestorLink = investorLink;
            //var status = investorLink.Status;

            ////Get InvestorLink detail
            //if (status != EnumStatus.Deleted)
            //{

            //    List<ReportingInvestorLink> lst = _context.ReportingInvestorLink
            //                       .FromSql("ups_GetSubInvestors @p0, @p1", id, status)
            //                       .ToList();
            //    model.ReportingInvestorLink = lst;
            //}
            //else
            //{
            //    model.ReportingInvestorLink = null;
            //}

            //using DI
            var model =  _investorLink.GetInvestorLinkSubInvestors(id);

            return View(model);
        }

        // POST: InvestorLink/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var investorLink = await _context.InvestorLinks.FindAsync(id);

            //if (investorLink.Status != EnumStatus.Deployed)
            //{
            //    _context.InvestorLinks.Remove(investorLink);


            //}
            //else
            //{
            //    _context.ReportingInvestorLink.FromSql("ups_BackoutSubInvestors @p0", id);
            //    //TODO: Get Reason Code
            //    investorLink.DeletedReason = "Deleted From Production";
            //    // investorLink.DeletedSubInvestorCount = rawsAffected.Count();
            //}

            _investorLink.DeleteInvestorLinkSubInvestors(id);

            investorLink.Status = EnumStatus.Deleted;
            investorLink.DeletedBy = User.Identity.Name;
            investorLink.DeletedDate = DateTime.Now;
            await _context.SaveChangesAsync();

           
            return RedirectToAction(nameof(Index));
        }

        // GET: InvestorLink/Approve/5
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Approve(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var investorLink = await _context.InvestorLinks
            //    .FirstOrDefaultAsync(m => m.InvestorSetupId == id);

            var investorLink = _investorLink.GetInvestorLinkSubInvestors(id);

            if (investorLink == null)
            {
                return NotFound();
            }

            return View(investorLink);
        }

        // POST: InvestorLink/Approve/5
        [HttpPost, ActionName("Approve")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> ApproveConfirmed(int id)
        {
            var investorLink = await _context.InvestorLinks.FindAsync(id);

            if (investorLink.Status == EnumStatus.New)
            {
                investorLink.Status = EnumStatus.Approved;
                investorLink.ApprovedDate = DateTime.Now;
                investorLink.ApprovedBy = User.Identity.Name;

                await _context.SaveChangesAsync();

            }
            else
            {
                ViewData["ApproveError"] = "Only NEW investor setup can be approved";
            }

            //var investorri = await _context.ReportingInvestorLinkStage.FindAsync(1, "000002000","00009");
            //_context.ReportingInvestorLinkStage.Remove(investorri);
            //await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: InvestorLink/Approve/5
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Deploy(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var investorLink = await _context.InvestorLinks
            //    .FirstOrDefaultAsync(m => m.InvestorSetupId == id);

            var investorLink =  _investorLink.GetInvestorLinkSubInvestors(id);

            if (investorLink == null)
            {
                return NotFound();
            }

            return View(investorLink);
        }

        // POST: InvestorLink/Deploy/5
        [HttpPost, ActionName("Deploy")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeployConfirmed(int id)
        {
            var investorLink = await _context.InvestorLinks.FindAsync(id);
       
            if(investorLink.Status == EnumStatus.Approved)
            {
                _context.Database.ExecuteSqlCommand("ups_InsertNewSubInvestors @p0", id);

                investorLink.Status = EnumStatus.Deployed;
                investorLink.DeployedDate = DateTime.Now;
                investorLink.DeployedBy = User.Identity.Name;

                await _context.SaveChangesAsync();

            }
            else
            {
                ViewData["DeployError"] = "Approval is needed before deploying to Production";

                return View("Views/InvestorLink/Deploy.cshtml");
            }

            //var investorri = await _context.ReportingInvestorLinkStage.FindAsync(1, "000002000","00009");
            //_context.ReportingInvestorLinkStage.Remove(investorri);
            //await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        private bool InvestorLinkExists(int id)
        {
            return  _context.InvestorLinks.Any(e => e.InvestorSetupId == id);
        }
    }
}

SubInvestorSetup/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser>  signInManager;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SubInvestor Setup</title>

    <environment include="Development">
        @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/boostrap_Lumen.css" />*@
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              @*asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"*@
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="investorLink" asp-action="Index">SubInvestor Setup</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="InvestorLink" asp-action="Index">Home</a>
                    </li>
                </ul>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-controller="account" asp-action="logout">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout: @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"asp-controller="account" asp-action="register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="account" asp-action="login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SubInvestorSetup - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

SubInvestorSetup/Views/Shared/_ReportingInvestorLink.cshtml
@model IEnumerable<SubInvestorSetup.Models.ReportingInvestorLink>

@{
    ViewData["Title"] = "Details";
}

<h4>InvestorReportingLink</h4>

<table class="table table-hover table-responsive-sm">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RI_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.INVESTOR_NBR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.INVESTOR_SUB)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RI_Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.INVESTOR_NBR)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.INVESTOR_SUB)
                </td>
            </tr>
        }
    </tbody>
</table>